<a href="https://colab.research.google.com/github/mkromah/gbm-multisource-biomarker-project/blob/main/Note_Book%2003_xena_data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook 03 — XENA Data Preparation

In [ ]:
# ============================================================
# Step 1: Mount Google Drive
# ============================================================
# This reconnects the Colab session to Google Drive so the
# notebook can access the project files stored in Drive.
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# ============================================================
# Step 2: Define shared project paths
# ============================================================

import os
import gzip
import pandas as pd

PROJECT_NAME = "Glioma_ML_Biomarker_Project"
BASE_DIR = f"/content/drive/MyDrive/{PROJECT_NAME}"

DATA_DIR = f"{BASE_DIR}/data"
RAW_DIR = f"{DATA_DIR}/raw"
PROCESSED_DIR = f"{DATA_DIR}/processed"

XENA_DIR = f"{RAW_DIR}/XENA"

print("Project root:", BASE_DIR)
print("XENA raw-data folder:", XENA_DIR)

Project root: /content/drive/MyDrive/Glioma_ML_Biomarker_Project
XENA raw-data folder: /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA

In [ ]:
# ============================================================
# Step 3: Define XENA file paths
# ============================================================

XENA_PHENOTYPE_FILE = f"{XENA_DIR}/TcgaTargetGTEX_phenotype.txt.gz"
XENA_EXPRESSION_FILE = f"{XENA_DIR}/TcgaTargetGtex_rsem_gene_tpm.gz"
XENA_PROBEMAP_FILE = f"{XENA_DIR}/probeMap_gencode.v23.annotation.gene.probemap"

print("Phenotype file:", XENA_PHENOTYPE_FILE)
print("Expression file:", XENA_EXPRESSION_FILE)
print("Probe-map file:", XENA_PROBEMAP_FILE)

Phenotype file: /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA/TcgaTargetGTEX_phenotype.txt.gz
Expression file: /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA/TcgaTargetGtex_rsem_gene_tpm.gz
Probe-map file: /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA/probeMap_gencode.v23.annotation.gene.probemap

In [ ]:
# ============================================================
# Step 4: Verify that the XENA files exist
# ============================================================

xena_file_paths = {
    "XENA_PHENOTYPE_FILE": XENA_PHENOTYPE_FILE,
    "XENA_EXPRESSION_FILE": XENA_EXPRESSION_FILE,
    "XENA_PROBEMAP_FILE": XENA_PROBEMAP_FILE
}

for file_name, file_path in xena_file_paths.items():
    exists = os.path.exists(file_path)
    status = "FOUND" if exists else "MISSING"
    print(f"{file_name}: {status} -> {file_path}")

XENA_PHENOTYPE_FILE: FOUND -> /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA/TcgaTargetGTEX_phenotype.txt.gz
XENA_EXPRESSION_FILE: FOUND -> /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA/TcgaTargetGtex_rsem_gene_tpm.gz
XENA_PROBEMAP_FILE: FOUND -> /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA/probeMap_gencode.v23.annotation.gene.probemap

In [ ]:
# ============================================================
# Step 5: Load the XENA phenotype metadata safely
# ============================================================
xena_pheno_df = pd.read_csv(
    XENA_PHENOTYPE_FILE,
    sep="\t",
    compression="gzip",
    encoding="latin1"
)

print("XENA phenotype metadata loaded successfully.")
print("Shape:", xena_pheno_df.shape)

XENA phenotype metadata loaded successfully.
Shape: (19131, 7)

In [ ]:
print("First 5 rows of the phenotype table:")
display(xena_pheno_df.head())

print("\nColumn names:")
print(list(xena_pheno_df.columns))

First 5 rows of the phenotype table:

,sample,detailed_category,primary disease or tissue,_primary_site,_sample_type,_gender,_study
0,TCGA-V4-A9EE-01,Uveal Melanoma,Uveal Melanoma,Eye,Primary Tumor,Male,TCGA
1,TCGA-VD-AA8N-01,Uveal Melanoma,Uveal Melanoma,Eye,Primary Tumor,Male,TCGA
2,TCGA-V4-A9EI-01,Uveal Melanoma,Uveal Melanoma,Eye,Primary Tumor,Male,TCGA
3,TCGA-VD-AA8O-01,Uveal Melanoma,Uveal Melanoma,Eye,Primary Tumor,Male,TCGA
4,TCGA-WC-A888-01,Uveal Melanoma,Uveal Melanoma,Eye,Primary Tumor,Male,TCGA

Column names:
['sample', 'detailed_category', 'primary disease or tissue', '_primary_site', '_sample_type', '_gender', '_study']

In [ ]:
# ============================================================
# Step 7: List all disease categories
# ============================================================

disease_counts = xena_pheno_df["detailed_category"].value_counts()

print("Number of unique disease categories:", disease_counts.shape[0])

disease_counts.head(20)

Number of unique disease categories: 93

detailed_category
Breast Invasive Carcinoma              1212
Kidney Clear Cell Carcinoma             603
Lung Adenocarcinoma                     574
Thyroid Carcinoma                       571
Head & Neck Squamous Cell Carcinoma     564
Prostate Adenocarcinoma                 548
Lung Squamous Cell Carcinoma            548
Brain Lower Grade Glioma                523
Skin Cutaneous Melanoma                 470
Stomach Adenocarcinoma                  450
Ovarian Serous Cystadenocarcinoma       427
Bladder Urothelial Carcinoma            426
Liver Hepatocellular Carcinoma          421
Muscle - Skeletal                       396
Acute Myeloid Leukemia                  369
Whole Blood                             337
Colon Adenocarcinoma                    331
Skin - Sun Exposed (Lower Leg)          324
Kidney Papillary Cell Carcinoma         321
Adipose - Subcutaneous                  318
Name: count, dtype: int64

In [ ]:
# ============================================================
# Step 8: Check for Glioblastoma samples safely
# ============================================================

gbm_preview = xena_pheno_df[
    xena_pheno_df["detailed_category"].str.contains("Glioblastoma", case=False, na=False)
]

print("Number of rows matching 'Glioblastoma':", gbm_preview.shape[0])
display(gbm_preview.head())

Number of rows matching 'Glioblastoma': 171

,sample,detailed_category,primary disease or tissue,_primary_site,_sample_type,_gender,_study
7025,TCGA-06-0675-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA
7026,TCGA-06-0678-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA
7027,TCGA-06-0680-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA
7028,TCGA-06-0681-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA
7029,TCGA-06-AABW-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA

In [ ]:
# ============================================================
# Step 9: List glioma-related disease labels
# ============================================================

glioma_like = xena_pheno_df[
    xena_pheno_df["detailed_category"].str.contains("Glioma|Glioblastoma", case=False, na=False)
]["detailed_category"].value_counts()

print("Glioma-related categories found:")
display(glioma_like)

Glioma-related categories found:

detailed_category
Brain Lower Grade Glioma            523
Pheochromocytoma & Paraganglioma    185
Glioblastoma Multiforme             171
Name: count, dtype: int64

In [ ]:
# ============================================================
# Step 10: Extract glioma cohort from phenotype table
# ============================================================

glioma_categories = [
    "Brain Lower Grade Glioma",
    "Glioblastoma Multiforme"
]

glioma_pheno_df = xena_pheno_df[
    xena_pheno_df["detailed_category"].isin(glioma_categories)
].copy()

print("Glioma cohort extracted.")
print("Number of samples:", glioma_pheno_df.shape[0])

glioma_pheno_df.head()

Glioma cohort extracted.
Number of samples: 694

,sample,detailed_category,primary disease or tissue,_primary_site,_sample_type,_gender,_study
7025,TCGA-06-0675-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA
7026,TCGA-06-0678-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA
7027,TCGA-06-0680-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA
7028,TCGA-06-0681-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA
7029,TCGA-06-AABW-11,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Solid Tissue Normal,NaN,TCGA

In [ ]:
# ============================================================
# Step 11: Keep only primary tumor samples
# ============================================================

glioma_tumor_df = glioma_pheno_df[
    glioma_pheno_df["_sample_type"] == "Primary Tumor"
].copy()

print("Primary tumor samples retained.")
print("Number of tumor samples:", glioma_tumor_df.shape[0])

glioma_tumor_df.head()

Primary tumor samples retained.
Number of tumor samples: 662

,sample,detailed_category,primary disease or tissue,_primary_site,_sample_type,_gender,_study
7043,TCGA-41-2571-01,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Primary Tumor,Male,TCGA
7044,TCGA-16-0846-01,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Primary Tumor,Male,TCGA
7045,TCGA-06-2559-01,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Primary Tumor,Male,TCGA
7046,TCGA-32-2634-01,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Primary Tumor,Male,TCGA
7047,TCGA-06-2562-01,Glioblastoma Multiforme,Glioblastoma Multiforme,Brain,Primary Tumor,Male,TCGA

In [ ]:
# ============================================================
# Step 12: Extract sample IDs for the glioma tumor cohort
# ============================================================

glioma_sample_ids = glioma_tumor_df["sample"].tolist()

print("Number of glioma tumor samples:", len(glioma_sample_ids))

print("\nFirst 10 sample IDs:")
print(glioma_sample_ids[:10])

Number of glioma tumor samples: 662

First 10 sample IDs:
['TCGA-41-2571-01', 'TCGA-16-0846-01', 'TCGA-06-2559-01', 'TCGA-32-2634-01', 'TCGA-06-2562-01', 'TCGA-32-2632-01', 'TCGA-02-0047-01', 'TCGA-06-2557-01', 'TCGA-76-4925-01', 'TCGA-06-0878-01']

In [ ]:
# ============================================================
# Step 13: Inspect expression matrix header
# ============================================================

import gzip

with gzip.open(XENA_EXPRESSION_FILE, "rt") as f:
    header_line = f.readline()

expression_columns = header_line.strip().split("\t")

print("Number of columns in expression matrix:", len(expression_columns))

print("\nFirst 20 columns:")
print(expression_columns[:20])

Number of columns in expression matrix: 19132

First 20 columns:
['sample', 'GTEX-S4Q7-0003-SM-3NM8M', 'TCGA-19-1787-01', 'TCGA-S9-A7J2-01', 'GTEX-QV31-1626-SM-2S1QC', 'TCGA-G3-A3CH-11', 'TCGA-B5-A5OE-01', 'GTEX-13QIC-0011-R1a-SM-5O9CJ', 'TCGA-B2-5641-11', 'GTEX-ZPCL-0126-SM-4WWC8', 'TARGET-20-PANGDN-09', 'GTEX-S33H-1226-SM-4AD69', 'GTEX-X88G-0426-SM-47JZ5', 'TCGA-C8-A1HL-01', 'TCGA-EW-A2FS-01', 'GTEX-ZAKK-0326-SM-5EGHA', 'GTEX-1399S-1726-SM-5L3DI', 'GTEX-ZF29-0926-SM-4WKFZ', 'TCGA-IR-A3L7-01', 'TCGA-05-4420-01']

In [ ]:
glioma_sample_ids

['TCGA-41-2571-01',
 'TCGA-16-0846-01',
 'TCGA-06-2559-01',
 'TCGA-32-2634-01',
 'TCGA-06-2562-01',
 'TCGA-32-2632-01',
 'TCGA-02-0047-01',
 'TCGA-06-2557-01',
 'TCGA-76-4925-01',
 'TCGA-06-0878-01',
 'TCGA-08-0386-01',
 'TCGA-26-5132-01',
 'TCGA-26-5134-01',
 'TCGA-06-0158-01',
 'TCGA-28-5204-01',
 'TCGA-28-5213-01',
 'TCGA-32-1980-01',
 'TCGA-06-0644-01',
 'TCGA-28-5207-01',
 'TCGA-14-1825-01',
 'TCGA-19-2620-01',
 'TCGA-06-0187-01',
 'TCGA-06-0743-01',
 'TCGA-14-0787-01',
 'TCGA-76-4926-01',
 'TCGA-06-0219-01',
 'TCGA-06-5413-01',
 'TCGA-28-5220-01',
 'TCGA-41-2572-01',
 'TCGA-06-0744-01',
 'TCGA-27-1831-01',
 'TCGA-32-5222-01',
 'TCGA-06-2567-01',
 'TCGA-15-0742-01',
 'TCGA-06-0184-01',
 'TCGA-06-5859-01',
 'TCGA-27-2523-01',
 'TCGA-28-5218-01',
 'TCGA-06-0141-01',
 'TCGA-06-0190-01',
 'TCGA-12-0821-01',
 'TCGA-27-2528-01',
 'TCGA-32-2615-01',
 'TCGA-06-5414-01',
 'TCGA-06-0646-01',
 'TCGA-06-5415-01',
 'TCGA-12-0619-01',
 'TCGA-12-3652-01',
 'TCGA-19-2629-01',
 'TCGA-06-0745-01',
 'TCGA-06-2565-01',
 'TCGA-26-5133-01',
 'TCGA-28-2499-01',
 'TCGA-32-1970-01',
 'TCGA-06-5856-01',
 'TCGA-76-4927-01',
 'TCGA-06-0156-01',
 'TCGA-14-1829-01',
 'TCGA-27-1830-01',
 'TCGA-19-5960-01',
 'TCGA-27-1834-01',
 'TCGA-27-2524-01',
 'TCGA-06-0130-01',
 'TCGA-06-0174-01',
 'TCGA-14-0789-01',
 'TCGA-02-2485-01',
 'TCGA-06-0686-01',
 'TCGA-06-0747-01',
 'TCGA-28-1753-01',
 'TCGA-28-5208-01',
 'TCGA-28-5216-01',
 'TCGA-06-5411-01',
 'TCGA-19-2624-01',
 'TCGA-06-0749-01',
 'TCGA-06-2564-01',
 'TCGA-06-0132-01',
 'TCGA-12-0618-01',
 'TCGA-14-0781-01',
 'TCGA-19-1787-01',
 'TCGA-27-2519-01',
 'TCGA-41-3915-01',
 'TCGA-06-0211-01',
 'TCGA-06-0238-01',
 'TCGA-12-3650-01',
 'TCGA-28-2514-01',
 'TCGA-28-1747-01',
 'TCGA-02-2483-01',
 'TCGA-06-0138-01',
 'TCGA-06-0750-01',
 'TCGA-26-1442-01',
 'TCGA-06-0139-01',
 'TCGA-06-0178-01',
 'TCGA-19-4065-01',
 'TCGA-27-1837-01',
 'TCGA-27-2521-01',
 'TCGA-06-0129-01',
 'TCGA-06-0882-01',
 'TCGA-15-1444-01',
 'TCGA-76-4928-01',
 'TCGA-06-1804-01',
 'TCGA-27-2526-01',
 'TCGA-06-5412-01',
 'TCGA-26-5136-01',
 'TCGA-28-2509-01',
 'TCGA-19-2625-01',
 'TCGA-32-1982-01',
 'TCGA-76-4929-01',
 'TCGA-06-2558-01',
 'TCGA-06-5418-01',
 'TCGA-14-0871-01',
 'TCGA-06-0649-01',
 'TCGA-06-0210-01',
 'TCGA-06-2563-01',
 'TCGA-06-5410-01',
 'TCGA-26-5135-01',
 'TCGA-76-4931-01',
 'TCGA-14-0817-01',
 'TCGA-28-2513-01',
 'TCGA-28-5209-01',
 'TCGA-26-5139-01',
 'TCGA-14-0790-01',
 'TCGA-06-0125-01',
 'TCGA-06-0157-01',
 'TCGA-19-1390-01',
 'TCGA-41-4097-01',
 'TCGA-02-0055-01',
 'TCGA-12-1597-01',
 'TCGA-28-5215-01',
 'TCGA-12-5295-01',
 'TCGA-14-1034-01',
 'TCGA-06-0168-01',
 'TCGA-27-1832-01',
 'TCGA-41-5651-01',
 'TCGA-14-1823-01',
 'TCGA-12-5299-01',
 'TCGA-06-0645-01',
 'TCGA-19-2619-01',
 'TCGA-06-5408-01',
 'TCGA-06-2561-01',
 'TCGA-27-1835-01',
 'TCGA-14-2554-01',
 'TCGA-76-4932-01',
 'TCGA-16-1045-01',
 'TCGA-32-2616-01',
 'TCGA-32-4213-01',
 'TCGA-06-5417-01',
 'TCGA-06-5858-01',
 'TCGA-12-0616-01',
 'TCGA-12-3653-01',
 'TCGA-06-2569-01',
 'TCGA-06-5416-01',
 'TCGA-06-2570-01',
 'TCGA-28-2510-01',
 'TCGA-DU-A76K-01',
 'TCGA-HT-7616-01',
 'TCGA-HT-7687-01',
 'TCGA-E1-A7YS-01',
 'TCGA-DH-A669-01',
 'TCGA-DU-A5TT-01',
 'TCGA-FG-6690-01',
 'TCGA-S9-A89V-01',
 'TCGA-DU-7292-01',
 'TCGA-S9-A7R2-01',
 'TCGA-HW-A5KJ-01',
 'TCGA-CS-4941-01',
 'TCGA-DU-7306-01',
 'TCGA-HT-7475-01',
 'TCGA-DU-6393-01',
 'TCGA-HT-7882-01',
 'TCGA-HT-A61C-01',
 'TCGA-QH-A6CX-01',
 'TCGA-S9-A6UA-01',
 'TCGA-TQ-A7RP-01',
 'TCGA-VW-A8FI-01',
 'TCGA-WH-A86K-01',
 'TCGA-HT-8109-01',
 'TCGA-HW-A5KK-01',
 'TCGA-E1-A7YM-01',
 'TCGA-FG-6692-01',
 'TCGA-FG-A4MW-01',
 'TCGA-TM-A84J-01',
 'TCGA-FG-5964-01',
 'TCGA-HT-7477-01',
 'TCGA-HT-7854-01',
 'TCGA-HT-8107-01',
 'TCGA-HT-A74H-01',
 'TCGA-IK-8125-01',
 'TCGA-DB-5281-01',
 'TCGA-HT-7608-01',
 'TCGA-DU-A6S3-01',
 'TCGA-FG-A6IZ-01',
 'TCGA-HT-7694-01',
 'TCGA-WY-A85D-01',
 'TCGA-DB-5279-01',
 'TCGA-DB-A64O-01',
 'TCGA-DU-7013-01',
 'TCGA-DU-7014-01',
 'TCGA-HT-7688-01',
 'TCGA-CS-6186-01',
 'TCGA-FG-A4MU-01',
 'TCGA-HT-7684-01',
 'TCGA-S9-A6WD-01',
 'TCGA-VM-A8CD-01',
 'TCGA-E1-A7YD-01',
 'TCGA-HT-8110-01',
 'TCGA-S9-A7IX-01',
 'TCGA-DU-6410-01',
 'TCGA-DU-A7TB-01',
 'TCGA-HT-7875-01',
 'TCGA-DU-A7TJ-01',
 'TCGA-E1-A7YJ-01',
 'TCGA-HT-8011-01',
 'TCGA-DB-A64V-01',
 'TCGA-DU-6399-01',
 'TCGA-DU-A76L-01',
 'TCGA-FG-5962-01',
 'TCGA-HT-7467-01',
 'TCGA-HT-8105-01',
 'TCGA-QH-A65Z-01',
 'TCGA-VM-A8CA-01',
 'TCGA-DU-6394-01',
 'TCGA-DU-7301-01',
 'TCGA-HT-7677-01',
 'TCGA-HT-8106-01',
 'TCGA-DH-A66B-01',
 'TCGA-DU-6402-01',
 'TCGA-DU-A7TD-01',
 'TCGA-E1-A7YK-01',
 'TCGA-HT-7474-01',
 'TCGA-R8-A6ML-01',
 'TCGA-S9-A6UB-01',
 'TCGA-S9-A6WL-01',
 'TCGA-DU-8164-01',
 'TCGA-DU-A5TR-01',
 'TCGA-DU-A76R-01',
 'TCGA-QH-A6CV-01',
 'TCGA-TQ-A7RU-01',
 'TCGA-CS-4944-01',
 'TCGA-DH-A7US-01',
 'TCGA-HT-7604-01',
 'TCGA-S9-A6TV-01',
 'TCGA-S9-A6TY-01',
 'TCGA-DH-A66F-01',
 'TCGA-DH-A7UV-01',
 'TCGA-FG-7637-01',
 'TCGA-CS-6188-01',
 'TCGA-DU-5849-01',
 'TCGA-FG-7636-01',
 'TCGA-QH-A6XC-01',
 'TCGA-TM-A84F-01',
 'TCGA-DB-A75M-01',
 'TCGA-FG-A4MX-01',
 'TCGA-HT-8564-01',
 'TCGA-HT-A614-01',
 'TCGA-HT-A617-01',
 'TCGA-P5-A737-01',
 'TCGA-QH-A6X4-01',
 'TCGA-RY-A840-01',
 'TCGA-W9-A837-01',
 'TCGA-E1-A7YL-01',
 'TCGA-S9-A6TX-01',
 'TCGA-S9-A6U0-01',
 'TCGA-S9-A7R4-01',
 'TCGA-TM-A84R-01',
 'TCGA-E1-A7YO-01',
 'TCGA-RY-A83Y-01',
 'TCGA-RY-A847-01',
 'TCGA-F6-A8O4-01',
 'TCGA-HT-7479-01',
 'TCGA-TM-A7CA-01',
 'TCGA-VV-A829-01',
 'TCGA-CS-5395-01',
 'TCGA-CS-6670-01',
 'TCGA-DB-5280-01',
 'TCGA-DH-A7UU-01',
 'TCGA-HT-7692-01',
 'TCGA-IK-7675-01',
 'TCGA-QH-A6CW-01',
 'TCGA-S9-A7J1-01',
 'TCGA-DU-A5TS-01',
 'TCGA-E1-5304-01',
 'TCGA-E1-A7YU-01',
 'TCGA-HT-7485-01',
 'TCGA-S9-A6WP-01',
 'TCGA-E1-5302-01',
 'TCGA-FG-8188-01',
 'TCGA-HW-7490-01',
 'TCGA-QH-A6CS-01',
 'TCGA-S9-A7QZ-01',
 'TCGA-CS-5394-01',
 'TCGA-DB-A64P-01',
 'TCGA-DU-A7TG-01',
 'TCGA-HT-7620-01',
 'TCGA-R8-A6MK-01',
 'TCGA-S9-A6TW-01',
 'TCGA-S9-A89Z-01',
 'TCGA-TM-A84B-01',
 'TCGA-TM-A84M-01',
 'TCGA-CS-5393-01',
 'TCGA-DU-7019-01',
 'TCGA-HT-7481-01',
 'TCGA-HT-7855-01',
 'TCGA-HW-7487-01',
 'TCGA-HW-8322-01',
 'TCGA-P5-A5EV-01',
 'TCGA-P5-A5EZ-01',
 'TCGA-S9-A7IY-01',
 'TCGA-TQ-A7RH-01',
 'TCGA-DB-A4XB-01',
 'TCGA-E1-5303-01',
 'TCGA-HT-7472-01',
 'TCGA-HT-7605-01',
 'TCGA-HT-7881-01',
 'TCGA-HW-7489-01',
 'TCGA-QH-A6CY-01',
 'TCGA-QH-A6CZ-01',
 'TCGA-S9-A6TU-01',
 'TCGA-TQ-A7RR-01',
 'TCGA-CS-4943-01',
 'TCGA-FG-8185-01',
 'TCGA-HT-7470-01',
 'TCGA-HW-7486-01',
 'TCGA-DB-5275-01',
 'TCGA-HT-7478-01',
 'TCGA-HT-7611-01',
 'TCGA-HT-8114-01',
 'TCGA-HW-8320-01',
 'TCGA-S9-A6U9-01',
 'TCGA-TM-A84S-01',
 'TCGA-TQ-A7RG-01',
 'TCGA-WY-A85C-01',
 'TCGA-DU-A7T8-01',
 'TCGA-E1-A7Z4-01',
 'TCGA-FG-8182-01',
 'TCGA-HT-7856-01',
 'TCGA-HW-7491-01',
 'TCGA-HW-A5KM-01',
 'TCGA-P5-A5EU-01',
 'TCGA-P5-A72W-01',
 'TCGA-S9-A7R1-01',
 'TCGA-DB-5277-01',
 'TCGA-DB-A4XG-01',
 'TCGA-E1-5305-01',
 'TCGA-F6-A8O3-01',
 'TCGA-HT-7609-01',
 'TCGA-HT-A74O-01',
 'TCGA-S9-A6WE-01',
 'TCGA-DB-5273-01',
 'TCGA-DU-7007-01',
 'TCGA-DU-7299-01',
 'TCGA-DU-A5TP-01',
 'TCGA-HT-7480-01',
 'TCGA-HT-A74J-01',
 'TCGA-P5-A5F0-01',
 'TCGA-QH-A86X-01',
 'TCGA-S9-A6U5-01',
 'TCGA-VM-A8CB-01',
 'TCGA-DB-5276-01',
 'TCGA-DB-A4XD-01',
 'TCGA-DH-5141-01',
 'TCGA-DU-A7TA-01',
 'TCGA-DU-A7TC-01',
 'TCGA-DU-A7TI-01',
 'TCGA-HT-8111-01',
 'TCGA-TM-A84C-01',
 'TCGA-TQ-A7RN-01',
 'TCGA-TQ-A7RW-01',
 'TCGA-CS-6290-01',
 'TCGA-DU-6395-01',
 'TCGA-E1-5311-01',
 'TCGA-FG-7641-01',
 'TCGA-FG-8187-01',
 'TCGA-HT-7879-01',
 'TCGA-HW-8321-01',
 'TCGA-S9-A6WG-01',
 'TCGA-TM-A84L-01',
 'TCGA-TM-A84Q-01',
 'TCGA-DB-A4XA-01',
 'TCGA-DH-5143-01',
 'TCGA-DH-A7UT-01',
 'TCGA-DU-A76O-01',
 'TCGA-FG-6689-01',
 'TCGA-FG-8191-01',
 'TCGA-HT-7468-01',
 'TCGA-HT-7469-01',
 'TCGA-HT-7880-01',
 'TCGA-P5-A5F1-01',
 'TCGA-RY-A843-01',
 'TCGA-TM-A7C5-01',
 'TCGA-TM-A84I-01',
 'TCGA-DB-A75O-01',
 'TCGA-DH-5142-01',
 'TCGA-DU-5853-01',
 'TCGA-DU-8163-01',
 'TCGA-HT-7603-01',
 'TCGA-HT-7690-01',
 'TCGA-HT-7873-01',
 'TCGA-S9-A6WO-01',
 'TCGA-TQ-A7RK-01',
 'TCGA-TQ-A7RO-01',
 'TCGA-E1-A7YW-01',
 'TCGA-FG-7634-01',
 'TCGA-HT-7473-01',
 'TCGA-HT-7858-01',
 'TCGA-S9-A6U6-01',
 'TCGA-P5-A5ET-01',
 'TCGA-QH-A6X3-01',
 'TCGA-S9-A7R7-01',
 'TCGA-TQ-A7RV-01',
 'TCGA-DB-A4XC-01',
 'TCGA-HT-7476-01',
 'TCGA-HT-7676-01',
 'TCGA-KT-A74X-01',
 'TCGA-P5-A5F6-01',
 'TCGA-DU-6542-01',
 'TCGA-DU-7011-01',
 'TCGA-FN-7833-01',
 'TCGA-S9-A7J2-01',
 'TCGA-VM-A8CE-01',
 'TCGA-HT-A5RB-01',
 'TCGA-S9-A6U8-01',
 'TCGA-WY-A85B-01',
 'TCGA-FG-5963-01',
 'TCGA-FG-8181-01',
 'TCGA-CS-6666-01',
 'TCGA-HT-A61B-01',
 'TCGA-P5-A730-01',
 'TCGA-HT-7602-01',
 'TCGA-HT-8015-01',
 'TCGA-P5-A5EY-01',
 'TCGA-P5-A72X-01',
 'TCGA-DB-A64S-01',
 'TCGA-WY-A85A-01',
 'TCGA-TM-A84T-01',
 'TCGA-DB-5278-01',
 'TCGA-HT-7483-01',
 'TCGA-DU-7012-01',
 'TCGA-DU-A6S8-01',
 'TCGA-FG-A713-01',
 'TCGA-DU-A7T6-01',
 'TCGA-QH-A6X9-01',
 'TCGA-S9-A6WH-01',
 'TCGA-P5-A72U-01',
 'TCGA-HT-A5RC-01',
 'TCGA-DU-8167-01',
 'TCGA-DB-A64L-01',
 'TCGA-DU-6400-01',
 'TCGA-DB-A64W-01',
 'TCGA-HT-A5RA-01',
 'TCGA-HT-8010-01',
 'TCGA-P5-A72Z-01',
 'TCGA-DU-8161-01',
 'TCGA-E1-A7YN-01',
 'TCGA-DU-5874-01',
 'TCGA-DU-A5TU-01',
 'TCGA-E1-5307-01',
 'TCGA-DU-5852-01',
 'TCGA-DU-8162-01',
 'TCGA-FG-A87Q-01',
 'TCGA-HT-7607-01',
 'TCGA-TM-A84O-01',
 'TCGA-DU-6403-01',
 'TCGA-DU-7006-01',
 'TCGA-DU-8165-01',
 'TCGA-HT-7860-01',
 'TCGA-DH-A7UR-01',
 'TCGA-DU-6406-01',
 'TCGA-FG-6688-01',
 'TCGA-P5-A731-01',
 'TCGA-S9-A6WM-01',
 'TCGA-DU-7010-01',
 'TCGA-E1-A7YQ-01',
 'TCGA-E1-A7Z2-01',
 'TCGA-HT-7689-01',
 'TCGA-HT-A74K-01',
 'TCGA-QH-A6X5-01',
 'TCGA-CS-6668-01',
 'TCGA-DU-5854-01',
 'TCGA-DU-7018-01',
 'TCGA-DU-8158-01',
 'TCGA-DB-A64X-01',
 'TCGA-DH-5144-01',
 'TCGA-QH-A6X8-01',
 'TCGA-S9-A6WI-01',
 'TCGA-DB-A75K-01',
 'TCGA-DU-8168-01',
 'TCGA-HT-A4DS-01',
 'TCGA-P5-A77X-01',
 'TCGA-CS-5397-01',
 'TCGA-RY-A83Z-01',
 'TCGA-S9-A7QW-01',
 'TCGA-TM-A84G-01',
 'TCGA-CS-5396-01',
 'TCGA-DB-A4XH-01',
 'TCGA-DU-7294-01',
 'TCGA-DU-7300-01',
 'TCGA-FG-A70Z-01',
 'TCGA-R8-A6MO-01',
 'TCGA-FG-A6J3-01',
 'TCGA-P5-A733-01',
 'TCGA-QH-A6CU-01',
 'TCGA-S9-A7J3-01',
 'TCGA-DU-6405-01',
 'TCGA-HT-7693-01',
 'TCGA-HT-8104-01',
 'TCGA-HT-A4DV-01',
 'TCGA-HT-A619-01',
 'TCGA-FG-A710-01',
 'TCGA-VM-A8C8-01',
 'TCGA-DU-5855-01',
 'TCGA-FG-7643-01',
 'TCGA-HT-8113-01',
 'TCGA-DU-7302-01',
 'TCGA-E1-5319-01',
 'TCGA-HT-A5R9-01',
 'TCGA-R8-A73M-01',
 'TCGA-S9-A6TS-01',
 'TCGA-S9-A6U2-01',
 'TCGA-S9-A7IZ-01',
 'TCGA-WY-A85E-01',
 'TCGA-CS-5390-01',
 'TCGA-E1-A7YH-01',
 'TCGA-EZ-7264-01',
 'TCGA-FG-A60J-01',
 'TCGA-DU-A5TY-01',
 'TCGA-RY-A83X-01',
 'TCGA-DU-7290-01',
 'TCGA-HW-7495-01',
 'TCGA-KT-A7W1-01',
 'TCGA-S9-A7IQ-01',
 'TCGA-CS-4942-01',
 'TCGA-FG-A4MY-01',
 'TCGA-FG-A6J1-01',
 'TCGA-HT-7884-01',
 'TCGA-P5-A736-01',
 'TCGA-P5-A780-01',
 'TCGA-S9-A7R8-01',
 'TCGA-TM-A84H-01',
 'TCGA-VM-A8CF-01',
 'TCGA-DH-A66D-01',
 'TCGA-DU-5872-01',
 'TCGA-QH-A65V-01',
 'TCGA-TM-A7C3-01',
 'TCGA-E1-5318-01',
 'TCGA-FG-8186-01',
 'TCGA-HW-A5KL-01',
 'TCGA-TQ-A8XE-01',
 'TCGA-DB-A4XF-01',
 'TCGA-DU-7008-01',
 'TCGA-DU-7015-01',
 'TCGA-DU-7309-01',
 'TCGA-E1-A7Z6-01',
 'TCGA-HT-7874-01',
 'TCGA-P5-A5EX-01',
 'TCGA-TM-A7CF-01',
 'TCGA-TQ-A7RM-01',
 'TCGA-HT-8018-01',
 'TCGA-HW-7493-01',
 'TCGA-RY-A845-01',
 'TCGA-CS-6667-01',
 'TCGA-FG-5965-01',
 'TCGA-S9-A6TZ-01',
 'TCGA-TM-A7C4-01',
 'TCGA-DB-5270-01',
 'TCGA-DB-A64U-01',
 'TCGA-DH-5140-01',
 'TCGA-DU-7298-01',
 'TCGA-E1-5322-01',
 'TCGA-HT-A615-01',
 'TCGA-P5-A735-01',
 'TCGA-QH-A65R-01',
 'TCGA-QH-A870-01',
 'TCGA-S9-A6WN-01',
 'TCGA-TQ-A7RQ-01',
 'TCGA-DB-5274-01',
 'TCGA-DU-5871-01',
 'TCGA-DU-A6S2-01',
 'TCGA-FG-A87N-01',
 'TCGA-HT-7471-01',
 'TCGA-HT-A618-01',
 'TCGA-P5-A77W-01',
 'TCGA-TQ-A7RI-01',
 'TCGA-VM-A8C9-01',
 'TCGA-DB-A75L-01',
 'TCGA-HT-A616-01',
 'TCGA-P5-A5F2-01',
 'TCGA-S9-A7QX-01',
 'TCGA-VV-A86M-01',
 'TCGA-DU-6392-01',
 'TCGA-DU-6407-01',
 'TCGA-DU-A6S6-01',
 'TCGA-P5-A5F4-01',
 'TCGA-S9-A7QY-01',
 'TCGA-VW-A7QS-01',
 'TCGA-DU-5847-01',
 'TCGA-DU-5870-01',
 'TCGA-FG-A60K-01',
 'TCGA-FG-A60L-01',
 'TCGA-HT-8019-01',
 'TCGA-HW-8319-01',
 'TCGA-P5-A781-01',
 'TCGA-WY-A859-01',
 'TCGA-DB-A4X9-01',
 'TCGA-DU-A5TW-01',
 'TCGA-E1-A7YI-01',
 'TCGA-FG-8189-01',
 'TCGA-FG-A711-01',
 'TCGA-HT-A5R5-01',
 'TCGA-HT-A5R7-01',
 'TCGA-S9-A7IS-01',
 'TCGA-DU-7009-01',
 'TCGA-E1-A7YE-01',
 'TCGA-HT-7680-01',
 'TCGA-QH-A65S-01',
 'TCGA-WY-A858-01',
 'TCGA-CS-4938-01',
 'TCGA-DB-A64Q-01',
 'TCGA-DU-6396-01',
 'TCGA-DU-6401-01',
 'TCGA-E1-A7Z3-01',
 'TCGA-FG-7638-01',
 'TCGA-HT-7691-01',
 'TCGA-HT-7601-01',
 'TCGA-HT-7606-01',
 'TCGA-HT-7902-01',
 'TCGA-HT-8012-01',
 'TCGA-HT-8563-01',
 'TCGA-S9-A7J0-01',
 'TCGA-DU-8166-01',
 'TCGA-HT-7681-01',
 'TCGA-HT-7686-01',
 'TCGA-HT-7695-01',
 'TCGA-HT-8558-01',
 'TCGA-QH-A65X-01',
 'TCGA-S9-A7R3-01',
 'TCGA-DB-A4XE-01',
 'TCGA-DU-A6S7-01',
 'TCGA-E1-A7YY-01',
 'TCGA-FG-A4MT-01',
 'TCGA-TQ-A7RF-01',
 'TCGA-CS-6669-01',
 'TCGA-E1-A7YV-01',
 'TCGA-HT-8108-01',
 'TCGA-DB-A75P-01',
 'TCGA-HT-7610-01',
 'TCGA-TQ-A7RJ-01',
 'TCGA-TQ-A7RS-01',
 'TCGA-DB-A64R-01',
 'TCGA-DU-6404-01',
 'TCGA-HT-7857-01',
 'TCGA-VM-A8CH-01',
 'TCGA-DU-6408-01',
 'TCGA-FG-6691-01',
 'TCGA-QH-A6XA-01',
 'TCGA-HT-A74L-01',
 'TCGA-S9-A6U1-01',
 'TCGA-FG-A70Y-01',
 'TCGA-HT-7877-01',
 'TCGA-HT-A61A-01',
 'TCGA-P5-A5EW-01',
 'TCGA-HT-7482-01',
 'TCGA-R8-A6YH-01']

In [ ]:
# ============================================================
# Step 14: Identify expression columns for glioma samples
# ============================================================

expression_sample_ids = expression_columns[1:]  # skip gene column

glioma_expression_columns = [
    s for s in expression_sample_ids if s in glioma_sample_ids
]

print("Total expression samples:", len(expression_sample_ids))
print("Matched glioma samples:", len(glioma_expression_columns))

print("\nFirst 10 matched samples:")
print(glioma_expression_columns[:10])

Total expression samples: 19131
Matched glioma samples: 662

First 10 matched samples:
['TCGA-19-1787-01', 'TCGA-S9-A7J2-01', 'TCGA-E1-A7YI-01', 'TCGA-06-5412-01', 'TCGA-DU-7302-01', 'TCGA-DU-A7TI-01', 'TCGA-16-0846-01', 'TCGA-12-5299-01', 'TCGA-P5-A5EX-01', 'TCGA-HT-8563-01']

In [ ]:
# ============================================================
# Step 15: Extract glioma expression data from XENA matrix
# ============================================================

# Columns to load
columns_to_load = ["sample"] + glioma_expression_columns

# Load only required columns
xena_glioma_expr_df = pd.read_csv(
    XENA_EXPRESSION_FILE,
    sep="\t",
    compression="gzip",
    usecols=columns_to_load
)

print("XENA glioma expression matrix loaded successfully.")
print("Matrix shape:", xena_glioma_expr_df.shape)

XENA glioma expression matrix loaded successfully.
Matrix shape: (60498, 663)

In [ ]:
# ============================================================
# Step 16: Inspect extracted expression matrix
# ============================================================

print("First 5 rows of the matrix:")
display(xena_glioma_expr_df.head())

print("\nFirst 10 column names:")
print(list(xena_glioma_expr_df.columns[:10]))

First 5 rows of the matrix:

,sample,TCGA-19-1787-01,TCGA-S9-A7J2-01,TCGA-E1-A7YI-01,TCGA-06-5412-01,TCGA-DU-7302-01,TCGA-DU-A7TI-01,TCGA-16-0846-01,TCGA-12-5299-01,TCGA-P5-A5EX-01,...,TCGA-FG-7636-01,TCGA-DU-5847-01,TCGA-28-2509-01,TCGA-DU-6406-01,TCGA-06-2558-01,TCGA-06-0745-01,TCGA-TM-A84B-01,TCGA-DU-A76O-01,TCGA-CS-4944-01,TCGA-HT-7603-01
0,ENSG00000242268.2,-9.9658,0.2998,-0.4521,-4.2934,-2.5479,-0.6193,-0.8863,-2.8262,-3.0469,...,-9.9658,-0.8863,-9.9658,0.2762,-1.0862,-1.2481,1.1117,-9.9658,-9.9658,-9.9658
1,ENSG00000259041.1,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,...,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658
2,ENSG00000270112.3,-3.8160,-3.0469,-0.7346,0.1519,0.9115,-2.6349,-1.2481,-1.0559,-9.9658,...,-4.2934,-4.2934,-0.9686,-2.1140,-0.1504,1.2147,1.8242,-6.5064,-4.2934,1.0642
3,ENSG00000167578.16,5.2998,4.8881,5.7632,6.1687,5.6329,5.8709,6.1851,5.5732,5.6419,...,5.6094,6.1379,5.0721,6.0926,5.6879,6.0330,4.6809,6.2263,6.6567,6.8560
4,ENSG00000278814.1,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,...,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658,-9.9658

First 10 column names:
['sample', 'TCGA-19-1787-01', 'TCGA-S9-A7J2-01', 'TCGA-E1-A7YI-01', 'TCGA-06-5412-01', 'TCGA-DU-7302-01', 'TCGA-DU-A7TI-01', 'TCGA-16-0846-01', 'TCGA-12-5299-01', 'TCGA-P5-A5EX-01']

In [ ]:
# ============================================================
# Step 17: Transpose expression matrix
# ============================================================

# Set gene column as index
xena_glioma_expr_df = xena_glioma_expr_df.set_index("sample")

# Transpose matrix
xena_glioma_expr_t = xena_glioma_expr_df.T

print("Matrix transposed successfully.")

print("New shape:", xena_glioma_expr_t.shape)

Matrix transposed successfully.
New shape: (662, 60498)

In [ ]:
# ============================================================
# Step 18: Attach tumor labels
# ============================================================

# Extract sample labels from phenotype table
sample_labels = glioma_tumor_df[["sample", "detailed_category"]]

# Set index for merging
sample_labels = sample_labels.set_index("sample")

# Add label column to expression matrix
xena_glioma_expr_t["tumor_label"] = sample_labels.loc[
    xena_glioma_expr_t.index,
    "detailed_category"
]

print("Tumor labels added successfully.")

# Check distribution
print("\nLabel distribution:")
print(xena_glioma_expr_t["tumor_label"].value_counts())

Tumor labels added successfully.

Label distribution:
tumor_label
Brain Lower Grade Glioma    509
Glioblastoma Multiforme     153
Name: count, dtype: int64

In [ ]:
import numpy as np

In [ ]:
# ============================================================
# Step 19: Replace XENA missing value indicator
# ============================================================

XENA_MISSING_VALUE = -9.9658

xena_glioma_expr_t = xena_glioma_expr_t.replace(XENA_MISSING_VALUE, np.nan)

print("Missing value indicator replaced with NaN.")

Missing value indicator replaced with NaN.

In [ ]:
# ============================================================
# Step 20: Check missing values
# ============================================================

missing_counts = xena_glioma_expr_t.isna().sum().sum()

print("Total missing values in dataset:", missing_counts)

Total missing values in dataset: 21074113

In [ ]:
# ============================================================
# Step 21: Remove genes with too many missing values
# ============================================================

# Separate labels from expression matrix
labels = xena_glioma_expr_t["tumor_label"]
expr = xena_glioma_expr_t.drop(columns=["tumor_label"])

# Calculate allowed missing threshold
missing_threshold = int(expr.shape[0] * 0.2)

# Filter genes
expr_filtered = expr.dropna(axis=1, thresh=expr.shape[0] - missing_threshold)

print("Original gene count:", expr.shape[1])
print("Filtered gene count:", expr_filtered.shape[1])

Original gene count: 60498
Filtered gene count: 23626

In [ ]:
# ============================================================
# Step 22: Reattach tumor labels
# ============================================================

expr_filtered = expr_filtered.copy()
expr_filtered.loc[:, "tumor_label"] = labels

print("Dataset ready after missing-value filtering.")
print("Final dataset shape:", expr_filtered.shape)

Dataset ready after missing-value filtering.
Final dataset shape: (662, 23627)

In [ ]:
# ============================================================
# Step 23: Remove low-variance genes
# ============================================================

from sklearn.feature_selection import VarianceThreshold

# Separate features and labels
y = expr_filtered["tumor_label"]
X = expr_filtered.drop(columns=["tumor_label"])

# Apply variance filtering
variance_filter = VarianceThreshold(threshold=0.01)

X_var_array = variance_filter.fit_transform(X)

# Recover selected gene names
selected_genes = X.columns[variance_filter.get_support()]

# Rebuild as DataFrame
X_var = pd.DataFrame(
    X_var_array,
    index=X.index,
    columns=selected_genes
)

print("Genes before variance filtering:", X.shape[1])
print("Genes after variance filtering:", X_var.shape[1])
print("Filtered feature matrix shape:", X_var.shape)

Genes before variance filtering: 23626
Genes after variance filtering: 23626
Filtered feature matrix shape: (662, 23626)

In [ ]:
# ============================================================
# Step 24: Select top variable genes
# ============================================================

# Calculate variance for each gene
gene_variances = X.var(axis=0)

# Sort genes by variance
top_genes = gene_variances.sort_values(ascending=False).head(5000).index

# Subset dataset
X_var = X[top_genes]

print("Original gene count:", X.shape[1])
print("Selected high-variance genes:", X_var.shape[1])
print("New feature matrix shape:", X_var.shape)

Original gene count: 23626
Selected high-variance genes: 5000
New feature matrix shape: (662, 5000)

In [ ]:
# ============================================================
# Step 25: Reattach labels safely
# ============================================================

X_var = X_var.copy()
X_var.loc[:, "tumor_label"] = y

print("Final ML dataset shape:", X_var.shape)

Final ML dataset shape: (662, 5001)

In [ ]:
# ============================================================
# Step 26: Encode tumor labels
# ============================================================

label_mapping = {
    "Brain Lower Grade Glioma": 0,
    "Glioblastoma Multiforme": 1
}

# Separate features and labels
X_ml = X_var.drop(columns=["tumor_label"]).copy()
y_ml = X_var["tumor_label"].map(label_mapping)

print("Label encoding completed successfully.")

print("\nEncoded label distribution:")
print(y_ml.value_counts().sort_index())

Label encoding completed successfully.

Encoded label distribution:
tumor_label
0    509
1    153
Name: count, dtype: int64

In [ ]:
# ============================================================
# Step 27: Train-test split
# ============================================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_ml,
    y_ml,
    test_size=0.2,
    random_state=42,
    stratify=y_ml
)

print("Train-test split completed successfully.")

print("\nTraining set shape:", X_train.shape)
print("Test set shape:", X_test.shape)

print("\nTraining label distribution:")
print(y_train.value_counts().sort_index())

print("\nTest label distribution:")
print(y_test.value_counts().sort_index())

Train-test split completed successfully.

Training set shape: (529, 5000)
Test set shape: (133, 5000)

Training label distribution:
tumor_label
0    407
1    122
Name: count, dtype: int64

Test label distribution:
tumor_label
0    102
1     31
Name: count, dtype: int64

In [ ]:
# ============================================================
# Step 28: Train baseline Random Forest model
# ============================================================

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully.")

Random Forest model trained successfully.

In [ ]:
# ============================================================
# Step 29: Evaluate baseline Random Forest model
# ============================================================

from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

# Predictions
y_pred = rf_model.predict(X_test)
y_prob = rf_model.predict_proba(X_test)[:, 1]

# Metrics
accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

print("Baseline Random Forest Performance")
print("-" * 40)

print("Accuracy:", round(accuracy, 4))
print("ROC-AUC :", round(roc_auc, 4))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Baseline Random Forest Performance
----------------------------------------
Accuracy: 1.0
ROC-AUC : 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       102
           1       1.00      1.00      1.00        31

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133

In [ ]:
# ============================================================
# Step 30: Extract gene importance scores
# ============================================================

import pandas as pd

# Extract importance scores
importance_scores = rf_model.feature_importances_

# Create dataframe
importance_df = pd.DataFrame({
    "gene": X_train.columns,
    "importance": importance_scores
})

# Sort genes by importance
importance_df = importance_df.sort_values(
    by="importance",
    ascending=False
)

print("Top 10 most important genes:")
display(importance_df.head(10))

Top 10 most important genes:

                    gene  importance
1830   ENSG00000223551.1    0.030984
2170   ENSG00000234743.1    0.023894
4278   ENSG00000236058.3    0.023892
2317   ENSG00000217094.2    0.022190
2066  ENSG00000185834.10    0.019463
35     ENSG00000219928.2    0.017954
3253   ENSG00000244716.3    0.017885
3766   ENSG00000237973.1    0.017640
2772  ENSG00000167553.14    0.015972
2994   ENSG00000255639.2    0.013886

In [ ]:
# ============================================================
# Step 31: Save ranked biomarker genes
# ============================================================

import os

output_path = "/content/drive/MyDrive/Glioma_ML_Biomarker_Project/results"

os.makedirs(output_path, exist_ok=True)

importance_df.to_csv(
    f"{output_path}/xena_gene_importance_ranking.csv",
    index=False
)

print("Gene importance ranking saved successfully.")

Gene importance ranking saved successfully.

In [ ]:
# ============================================================
# Step 32: Load gene annotation map (Ensembl → Gene Symbol)
# ============================================================

PROBEMAP_FILE = "/content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA/probeMap_gencode.v23.annotation.gene.probemap"

gene_map = pd.read_csv(
    PROBEMAP_FILE,
    sep="\t"
)

print("Gene annotation map loaded successfully.")
print("Shape:", gene_map.shape)

gene_map.head()

Gene annotation map loaded successfully.
Shape: (60498, 6)

                  id          gene chrom  chromStart  chromEnd strand
0  ENSG00000223972.5       DDX11L1  chr1       11869     14409      +
1  ENSG00000227232.5        WASH7P  chr1       14404     29570      -
2  ENSG00000278267.1     MIR6859-1  chr1       17369     17436      -
3  ENSG00000243485.3  RP11-34P13.3  chr1       29554     31109      +
4  ENSG00000274890.1     MIR1302-2  chr1       30366     30503      +

In [ ]:
# ============================================================
# Step 33: Map Ensembl IDs to gene symbols
# ============================================================

# Remove version numbers from Ensembl IDs (e.g., ENSG00000223972.5 → ENSG00000223972)
importance_df["ensembl_id"] = importance_df["gene"].str.split(".").str[0]
gene_map["ensembl_id"] = gene_map["id"].str.split(".").str[0]

# Merge importance table with gene symbol mapping
importance_annotated = importance_df.merge(
    gene_map[["ensembl_id", "gene"]],
    on="ensembl_id",
    how="left"
)

# Rename columns for clarity
importance_annotated = importance_annotated.rename(
    columns={
        "gene_x": "ensembl_gene",
        "gene_y": "gene_symbol"
    }
)

print("Gene annotation completed.")

importance_annotated.head(10)

Gene annotation completed.

         ensembl_gene  importance       ensembl_id    gene_symbol
0   ENSG00000223551.1    0.030984  ENSG00000223551       TMSB4XP4
1   ENSG00000234743.1    0.023894  ENSG00000234743        EIF5AP4
2   ENSG00000236058.3    0.023892  ENSG00000236058  RP11-215A21.2
3   ENSG00000217094.2    0.022190  ENSG00000217094        PPIAP31
4  ENSG00000185834.10    0.019463  ENSG00000185834        RPL12P4
5   ENSG00000219928.2    0.017954  ENSG00000219928    RP11-40C6.2
6   ENSG00000244716.3    0.017885  ENSG00000244716   RP11-20O24.4
7   ENSG00000237973.1    0.017640  ENSG00000237973   RP5-857K21.6
8  ENSG00000167553.14    0.015972  ENSG00000167553         TUBA1C
9   ENSG00000255639.2    0.013886  ENSG00000255639  RP11-234B24.6

In [ ]:
# ============================================================
# Step 34: Extract top biomarker genes
# ============================================================

TOP_N = 20

top_biomarkers = importance_annotated.head(TOP_N)

print(f"Top {TOP_N} candidate biomarkers:")
display(top_biomarkers)

Top 20 candidate biomarkers:

          ensembl_gene  importance       ensembl_id    gene_symbol
0    ENSG00000223551.1    0.030984  ENSG00000223551       TMSB4XP4
1    ENSG00000234743.1    0.023894  ENSG00000234743        EIF5AP4
2    ENSG00000236058.3    0.023892  ENSG00000236058  RP11-215A21.2
3    ENSG00000217094.2    0.022190  ENSG00000217094        PPIAP31
4   ENSG00000185834.10    0.019463  ENSG00000185834        RPL12P4
5    ENSG00000219928.2    0.017954  ENSG00000219928    RP11-40C6.2
6    ENSG00000244716.3    0.017885  ENSG00000244716   RP11-20O24.4
7    ENSG00000237973.1    0.017640  ENSG00000237973   RP5-857K21.6
8   ENSG00000167553.14    0.015972  ENSG00000167553         TUBA1C
9    ENSG00000255639.2    0.013886  ENSG00000255639  RP11-234B24.6
10   ENSG00000223361.5    0.013546  ENSG00000223361        FTH1P10
11   ENSG00000100985.7    0.013461  ENSG00000100985           MMP9
12   ENSG00000236782.5    0.013412  ENSG00000236782   RP11-96L14.7
13   ENSG00000235508.3    0.012718  ENSG00000235508         RPS2P7
14   ENSG00000259032.2    0.012574  ENSG00000259032         ENSAP2
15   ENSG00000229419.1    0.012325  ENSG00000229419      RALGAPA1P
16   ENSG00000234782.3    0.012111  ENSG00000234782         TPT1P9
17   ENSG00000226085.3    0.011590  ENSG00000226085      UQCRFS1P1
18   ENSG00000214110.3    0.011005  ENSG00000214110         LDHAP4
19   ENSG00000213131.3    0.010988  ENSG00000213131        YWHAZP4