<a href="https://colab.research.google.com/github/mkromah/gbm-multisource-biomarker-project/blob/main/NoteBook%2002_data_ingestion_and_file_verification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Notebook 02 — Data Ingestion and File Verification

This notebook verifies that all raw datasets required for the glioma machine learning project are present and accessible from Google Drive.

**Mount Drive and load shared configuration**

In [ ]:
# ============================================================
# Step 1: Mount Google Drive and define shared project paths
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import os
from pathlib import Path
import pandas as pd

PROJECT_NAME = "Glioma_ML_Biomarker_Project"
BASE_DIR = f"/content/drive/MyDrive/{PROJECT_NAME}"

DATA_DIR = f"{BASE_DIR}/data"
RAW_DIR = f"{DATA_DIR}/raw"
PROCESSED_DIR = f"{DATA_DIR}/processed"

CGGA_DIR = f"{RAW_DIR}/CGGA"
XENA_DIR = f"{RAW_DIR}/XENA"
GEO_DIR = f"{RAW_DIR}/GEO"

RESULTS_DIR = f"{BASE_DIR}/results"
FIGURES_DIR = f"{RESULTS_DIR}/figures"
TABLES_DIR = f"{RESULTS_DIR}/tables"
MODELS_DIR = f"{BASE_DIR}/models"

print("Shared project configuration loaded successfully.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Shared project configuration loaded successfully.

In [ ]:
# ============================================================
# Step 2: Verify that the main project directories exist
# ============================================================

project_directories = {
    "BASE_DIR": BASE_DIR,
    "DATA_DIR": DATA_DIR,
    "RAW_DIR": RAW_DIR,
    "CGGA_DIR": CGGA_DIR,
    "XENA_DIR": XENA_DIR,
    "GEO_DIR": GEO_DIR,
    "PROCESSED_DIR": PROCESSED_DIR,
    "RESULTS_DIR": RESULTS_DIR,
    "FIGURES_DIR": FIGURES_DIR,
    "TABLES_DIR": TABLES_DIR,
    "MODELS_DIR": MODELS_DIR
}

for name, path in project_directories.items():
    status = "Exists" if os.path.exists(path) else "Missing"
    print(f"{name:<15} | {status:<7} | {path}")

BASE_DIR        | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project
DATA_DIR        | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data
RAW_DIR         | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw
CGGA_DIR        | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/CGGA
XENA_DIR        | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA
GEO_DIR         | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/GEO
PROCESSED_DIR   | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/processed
RESULTS_DIR     | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/results
FIGURES_DIR     | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/results/figures
TABLES_DIR      | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/results/tables
MODELS_DIR      | Exists  | /content/drive/MyDrive/Glioma_ML_Biomarker_Project/models

In [ ]:
# ============================================================
# Step 2 — Verify raw-data folders


import os

raw_folders = {
    "CGGA_DIR": CGGA_DIR,
    "XENA_DIR": XENA_DIR,
    "GEO_DIR": GEO_DIR
}

for folder_name, folder_path in raw_folders.items():
    exists = os.path.exists(folder_path)
    status = "FOUND" if exists else "MISSING"
    print(f"{folder_name}: {status} -> {folder_path}")

CGGA_DIR: FOUND -> /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/CGGA
XENA_DIR: FOUND -> /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA
GEO_DIR: FOUND -> /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/GEO

In [ ]:
# ============================================================
# Step 3: Define a helper function to inspect folder contents
# ============================================================

def inspect_folder(folder_path):
    folder = Path(folder_path)

    if not folder.exists():
        print(f"[Missing folder] {folder_path}")
        return pd.DataFrame()

    items = list(folder.iterdir())

    if len(items) == 0:
        print(f"[Empty folder] {folder_path}")
        return pd.DataFrame()

    records = []

    for item in sorted(items):
        item_type = "Folder" if item.is_dir() else "File"
        size_mb = round(item.stat().st_size / (1024 ** 2), 2) if item.is_file() else None

        records.append({
            "name": item.name,
            "type": item_type,
            "size_mb": size_mb,
            "path": str(item)
        })

    df = pd.DataFrame(records)
    print(f"\nFolder inspected: {folder_path}")
    print(f"Total items found: {len(df)}")
    return df

In [ ]:
# ============================================================
# Step 4: Inspect the CGGA raw-data folder
# ============================================================

cgga_files = inspect_folder(CGGA_DIR)
cgga_files

Folder inspected: /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/CGGA
Total items found: 2

,name,type,size_mb,path
0,CGGA.mRNAseq_693.RSEM-genes.20200506.txt,File,79.67,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...
1,CGGA.mRNAseq_693_clinical.20200506.txt,File,0.05,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...

In [ ]:
# ============================================================
# Step 5: Inspect the XENA raw-data folder
# ============================================================

xena_files = inspect_folder(XENA_DIR)
xena_files

Folder inspected: /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/XENA
Total items found: 3

,name,type,size_mb,path
0,TcgaTargetGTEX_phenotype.txt.gz,File,0.13,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...
1,TcgaTargetGtex_rsem_gene_tpm.gz,File,1261.95,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...
2,probeMap_gencode.v23.annotation.gene.probemap,File,3.09,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...

In [ ]:
# ============================================================
# Step 6: Inspect the GEO raw-data folder

geo_files = inspect_folder(GEO_DIR)
geo_files

Folder inspected: /content/drive/MyDrive/Glioma_ML_Biomarker_Project/data/raw/GEO
Total items found: 1

,name,type,size_mb,path
0,GSE16011_series_matrix.txt.gz,File,25.79,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...

In [ ]:
# ============================================================
# Step 7: Combine raw-data inventories across all sources
# ============================================================

def add_source_column(df, source_name):
    if df.empty:
        return df
    df = df.copy()
    df.insert(0, "source", source_name)
    return df

inventory_frames = [
    add_source_column(cgga_files, "CGGA"),
    add_source_column(xena_files, "XENA"),
    add_source_column(geo_files, "GEO")
]

inventory_frames = [df for df in inventory_frames if not df.empty]

raw_inventory_df = pd.concat(inventory_frames, ignore_index=True)

print("Combined raw-data inventory created successfully.")
raw_inventory_df

Combined raw-data inventory created successfully.

,source,name,type,size_mb,path
0,CGGA,CGGA.mRNAseq_693.RSEM-genes.20200506.txt,File,79.67,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...
1,CGGA,CGGA.mRNAseq_693_clinical.20200506.txt,File,0.05,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...
2,XENA,TcgaTargetGTEX_phenotype.txt.gz,File,0.13,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...
3,XENA,TcgaTargetGtex_rsem_gene_tpm.gz,File,1261.95,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...
4,XENA,probeMap_gencode.v23.annotation.gene.probemap,File,3.09,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...
5,GEO,GSE16011_series_matrix.txt.gz,File,25.79,/content/drive/MyDrive/Glioma_ML_Biomarker_Pro...

In [ ]:
# ============================================================
# Step 8: Save the raw-data inventory table
# ============================================================

TABLES_DIR = f"{BASE_DIR}/results/tables"
os.makedirs(TABLES_DIR, exist_ok=True)

inventory_path = f"{TABLES_DIR}/raw_data_inventory.csv"

raw_inventory_df.to_csv(inventory_path, index=False)

print("Raw data inventory saved successfully.")
print("Location:", inventory_path)

Raw data inventory saved successfully.
Location: /content/drive/MyDrive/Glioma_ML_Biomarker_Project/results/tables/raw_data_inventory.csv